projectatomic/oci-systemd-hook

oci-systemd-hook.spec
Since we have removed dockerinit from /usr/libexec/docker, I think we should
standarize to to /usr/lib/docker/hooks.d for location of hooks.
The docker-1.10.1 package is looking here for this location now.
=> Move docker hooks to /usr/lib/docker/hooks.d

Makefile.am, configure.ac, src/systemdhook.c
Find all of the cgroup file systems under /sys/fs/cgroup and bind
mount them read/only into the container except for /sys/fs/cgroup/systemd
=> Mount all cgroup file systems on host system r/o into container

src/systemdhook.c
This fixes the double mounting issue for the cgroups mounts.
Also, taking out the #if 0 .. #endif block to enable the code.
@rhatdan PTAL
=> Fix cgroups mounting issues and enable it

README.md
Wildcard 'dnf-*' service causes failure to build.  Explicitly list
dnf-makecache.service instead.  Also update the base image, in case
newer base image breaks example build in some other way.
Signed-off-by: Chris Evich <cevich@redhat.com>
=> Update README.md example dockerfile run command

src/systemdhook.c
make it usable from OCI spec file as:
```
"hooks": {
"prestart": [
{
"path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
}
],
"poststop": [
{
"path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
}
]
}
```
runc does not pass any argument to the process, so read all the info
from the stdin JSON file.  The mount points are read from the
config.json file in the container bundle directory.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> oci-systemd-hook: work with OCI hooks

src/systemdhook.c
If env "container" not set, this program will report segment fault when
executed, this is caused by `strncmp(NULL, ...)`.
Adding a judgement of NULL can avoid this.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
=> Fix segment fault

src/systemdhook.c
we were using runc id for the machine-id which is wrong, as the runc
id is not an uuid.  Change it to use the $container_uuid environment
variable when defined.  As an effect, we mount the correct
/var/log/journal/%s directory in the container.
This means that containers using systemd must define a container_uuid=
environment variable.  To simplify this task for system containers, we
can automatically generate a new variable, so that the environment
block will look like:
"env": [
...
"container_uuid=$CONTAINER_UUID"
...
],
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> oci-systemd-hook: use $container_uuid= when the container has it

src/systemdhook.c
The defaults on the host system are /run and /tmp do not run with
NOEXEC, so we should not change the default inside of a container.
This is breaking certain workloads.
=> We should not be mounting /run and /tmp as NOEXEC

src/systemdhook.c
If the total memory on the system is less then the max memory in cgroup
then do not set memory limit on tmpfs, allow the kernel to set the default.
=> Fix the handling of memory allocation for tmpfs.

src/systemdhook.c
By changing the ifdef, you can now make the app using a command like
make CFLAGS="-D ARGS_CHECK=0" to compile oci-systemd-hook to always run.
Also fixed bogus comment.
=> Change ifdef ARGS_CHECK to if ARGS_CHECK to allow CFLAGS manipulation

src/systemdhook.c
images not based on rhel might not have the /run/secrets directory.  Do
not fail when it doesn't exist.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> oci-systemd-hook: do not fail if /run/secrets doesn't exist

src/systemdhook.c
This fixes the issue we saw with the /tmp being mounted outside of
the container using --tmpfs but not being seen by oci-systemd-hook
Also using this method see's the /run/secrets patch so we don't need
the special handling.
Also eliminates a whole bunch of code which is always good.
=> Remove all references to docker, using the runc method works fine.

README.md
Adds docker build example line that was implied but not specified
in the README.md file.
=> Update README.md example with implied build step

README.md
The docker build had a weird dash in it, I'm not sure how it got there.  If cut/pasted the command would fail.  I've removed the bad dash and have replaced it with a valid one.
=> Touch up a minor typo in README.md

src/systemdhook.c
systemdhook exits through the same error handling code path if it fails
to open the config file or if the config file name is not specified via
'bundlePath' in stateData. This patch ensures that the latter error is
reported explicitly:
Failed to open config file: bundlePath not found in state
Also, call snprintf() to fill the 'config_file_name' buffer instead of
sprintf() for better protection against buffer overflow.
=> improve error message if no 'bundlePath' in stateData

src/systemdhook.c
This pull request consists of three commits:
1. introduce the getJSONstring() function
2. call getJSONstring() to read state data from standard input
3. call getJSONstring() to read config data from bundlePath/config.json
=> refactor reading state and config data

src/systemdhook.c
The path bundle path passed to a container is called bundle, not bundlepath.
Also root is not in the state file, but can be retrieved from the config.json.
Signed-off-by: Dan Walsh <dwalsh@redhat.com>
=> Needs this change to work directly with runc and cri-o

README.md
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Adding the necessary packages to build oci-systemd-hook to the README.md file, much in the same manner as Buildah.   It's nice to have the list in advance rather than trying to figure out what's missing with each configure/make failure.
=> Add preinstall instructions to README.md

src/systemdhook.c
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Introduces a variable to pass with the docker run command to turn off the use of oci-systemd-hook.   When issuing the "docker run" command, the following command would be used to disable the hook:
docker run --env oci-systemd-hook=DISABLED
If disabled is not the value (any case) or the variable is not set, hook continues as normal.
=> Use env variable to disable oci-systemd-hook

README.md
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Adds information about the oci-systemd-hook=disabled environment variable for use with docker run.  This also touches up a few formatting issues here and there through out the document.
=> Add oci-systemd-hook=disabled info to README.md plus touch ups

src/systemdhook.c
In earlier versions of the runc frame work the rootfs path was passed
as a key with the initial json that was passed on the stdin and it was
automatically computed to be an absolute path.
This translation to an absolute path must be done in the hook based on
the bundlePath.  This allows the config.json to be relocated by the
container hosting system storage without modifying the config.json.
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
=> Allow container definitions where rootfs is not an absolute path

configure.ac, src/systemdhook.c
=> Debian expects /run/lock to be a tmpfs as well as /run

Makefile.am, oci-systemd-hook.json, oci-systemd-hook.spec
This will allow container runtimes like crio to only
execute hooks when needed
=> Add support for hooks json configuration

src/systemdhook.c
Remove compiler complaint
output container_id on all log messages
remove extra \\n from all log messages.
=> Cleanup code similar to oci-umount

README.md
Nowadays `dnf` doesn't whine if one types `yum`, so let's be
compatible with CentOS and use that.  Also fix up the error
handling (i.e. use `&&` instead of `;`).
=> README: Fix example Dockerfile error handling, change to use yum

oci-systemd-hook.spec, src/systemdhook.c
Attempts to set the SELinux label are causing MAC_ADMIN errors, because
the call is attempting to set the label to "", we should not be calling
the setfilecon call in that case.
=> Don't attempt to set the SELinux label if it is null or ""

README.md
=> README: Fix two "containers" -> "container's" typos

README.md
In 7ac5d7a7 (2015-11-23), we added atx-style markup for this header but neglegted to remove the Setext-style markup.  Both styles are discussed [here][1].
[1]: https://daringfireball.net/projects/markdown/syntax#header
=> REAMDE: Remove leftover Setext-style markup

README.md
The repository was renamed specs -> runtime-spec when the OCI added the image-spec project as a separate repository.
Also convert this to a reference-style link to make the text easier to read (no inline URL clutter) and the link easier to update (no surrounding English clutter).
=> README: Update OCI runtime spec link

src/systemdhook.c
=> systemd falls back to /run/log/journal not /run/journal

src/systemdhook.c
The current version of the oci-systemd-hooks changes the SELinux context of the /sys/fs/cgroup/systemd/system.slice directory on every launch of the systemd container, disrupting access to this directory for previously launched containers.
I checked it on a clean install of CentOS 7.6.
```
```
Default SELinux context on /sys/fs/cgroup/systemd/system.slice directory is system_u:object_r:cgroup_t:s0
```
drwxr-xr-x. root root system_u:object_r:cgroup_t:s0    /sys/fs/cgroup/systemd/system.slice
```
Now let's run our first container.
```
002fb057ce87c86732a1771c19d77407c2df23bff34c95041e3dd79b82267331
"ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c214,c860",
drwxr-xr-x. root root system_u:object_r:container_file_t:s0:c214,c860 /sys/fs/cgroup/systemd/system.slice
```
The context has …
=> Do not touch the parent directory
