- src/systemdhook.c
Whitespace cleanup and add static to functions.
> Code cleanup

- .gitignore
> Add the man page to .gitignore

- oci-systemd-hook.spec
> Modify installation location to /usr/libexec/oci/hooks.d

- src/systemdhook.c
Since the hooks are called after user mounts under /run are already setup
we re-order the mounts be inserting a tmpfs at /run and then moving the
uesr mounts over it.
> Fix order of mounts under /run

- src/systemdhook.c
> Add debugs to print directory path when mkdir fails

- .gitignore
> Fixup the name of files to ignore in .gitignore

- src/systemdhook.c
> /dev/init fix

- src/systemdhook.c
> Fix detection of docker to read the correct config file

- src/systemdhook.c
Created new function move_mounts which will handle moving all bind mounts off
of rootfs onto temporary file system.
Mounts a tmpfs on the path, and then moves the mount points back.
We want to use this for /run, /var/log and /tmp file systems.
> Fix /var/log and /tmp mount volume mounts to show up in container

- src/systemdhook.c
We were mounting a tmpfs on /var/log so that we could handle read-only
containers, the problem with this is that it will cover over other
content in /var/log that might be needed by other tools.  This patch
will ignore errors on creating the directory on /var/log/journal and rely on
the init system either working or failing with an error.
If a user wants to journalling to work, they need to make sure /var/log is
read/write or /var/log/journal is in the /var/log directory.
> Don't mount tmpfs on /var/log since it can cover other directories

- src/systemdhook.c
The content of config files is read into a buffer of fixed size
(currently CONFIGSZ is 65536 bytes) which imposes a limit on the
size of config files that systemdhook is able to parse. The patch
removes this limitation by allocating a buffer dynamically, based
on the actual config file size. The patch also fixes parse error
'trailing garbage' which could occur due to a missing NULL byte
that is expected to mark the end of the JSON string in the buffer.
As a 'bonus', the patch also fixes incorrect initialization of the
'errbuf' and 'stateData' variables.
> allocate configData dynamically

- src/systemdhook.c
Signed-off-by: TomSweeneyRedHat <tsweney@redhat.com>
Change the uid and gid values for the /sys/fs/cgroup/ directories to the value of root to avoid failures as noted in https://bugzilla.redhat.com/show_bug.cgi?id=1406684.  In particular when the username_namespace is enabled/set to 1 in /proc/cmdline and the --userns-remap parameter is used in the docker config file, the container would fail due to permission errors on the /sys/fs/cgroup/ directory tree.
> Set directories gid and uid to allow container access

- configure.ac
> Change configure.ac version to match rpm package.

- src/systemdhook.c
You can only MS_MOVE a directory to a directory, and a file to a file.
Currently we are only creating directories, so when a user tries to
mount a socket into a container it fails.
docker run -v /run/docker.sock:/run/docker.sock initcontainer
Fails
>  MS_MOVE content under /run, need to differentiate directories from files 

- configure.ac
> Update oci-systemd-hook version

- oci-systemd-hook.json
> Hooks are fired off via stage not stages

- src/systemdhook.c
When you run a systemd based container inside of a user namespace,
the mount options have to match exactly those of the existing mount.
So if you remount the mount point, with differenet options, you will
get permission denied.
> Make sure oci-systemd-hook remounts with the correct mount options

- configure.ac
- oci-systemd-hook.spec
Also update spec file to match Fedora spec file
> Bump version v0.1.15

- src/systemdhook.c
> Check stage environment variable in addition to argv[1] for stage

- src/systemdhook.c
> fix invalid /etc/machine-id

- configure.ac
- oci-systemd-hook.spec
> Bump version to 0.1.16

- configure.ac
- src/systemdhook.c
> Make sure SELinux is enabled before calling SELinux

- src/systemdhook.c
Inlcuding leaked objects and potential buffer overflow.
> Fix issues found by Coverity
